# Generated by Django 5.0.2 on 2024-03-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_product_product_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='safety_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
