# Generated by Django 5.0.2 on 2024-03-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_safety_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_sales',
        ),
    ]
